version: '3.2'
services:
    vault:
        image: vault
        container_name: vault
        ports:
            - "172:17.0.1:8200:8200"
        expose:
          - 8200
        restart: always
        volumes:
            - ./volumes/logs:/vault/logs
            - ./volumes/file:/vault/file
            - ./volumes/config:/vault/config
        cap_add:
            - IPC_LOCK
        entrypoint: vault server -config=/vault/config/vault.json
        networks:
            - utilities
            - dockerelk_elk
            - proxy
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.vault.entrypoints=http"
            - "traefik.http.routers.vault.rule=Host(`vault.huhta-lauri.dev`)"
            - "traefik.http.middlewares.vault-https-redirect.redirectscheme.scheme=https"
            - "traefik.http.routers.vault.middlewares=vault-https-redirect"
            - "traefik.http.routers.vault-secure.entrypoints=https"
            - "traefik.http.routers.vault-secure.rule=Host(`vault.huhta-lauri.dev`)"
            - "traefik.http.routers.vault-secure.tls=true"
            - "traefik.http.routers.vault-secure.tls.certresolver=http"
            - "traefik.http.routers.vault-secure.service=vault"
            - "traefik.http.services.vault.loadbalancer.server.port=8200"
            - "traefik.docker.network=proxy"

    traefik:
      image: traefik:latest
      container_name: traefik
      restart: unless-stopped
      security_opt:
        - no-new-privileges:true
      networks:
        - utilities
        - proxy
      ports:
        - 80:80
        - 443:443
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - ./traefik/data/traefik.yml:/traefik.yml:ro
        - ./traefik/data/acme.json:/acme.json
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik.entrypoints=http"
        - "traefik.http.routers.traefik.rule=Host(`traefik.huhta-lauri.dev`)"
        - "traefik.http.middlewares.traefik-auth.basicauth.users=magalorian:$$apr1$$.qEqWkW7$$LoSPOGXQpiHcUht/7Nn3K."
        - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
        - "traefik.http.routers.traefik-secure.entrypoints=https"
        - "traefik.http.routers.traefik-secure.rule=Host(`traefik.huhta-lauri.dev`)"
        - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
        - "traefik.http.routers.traefik-secure.tls=true"
        - "traefik.http.routers.traefik-secure.tls.certresolver=http"
        - "traefik.http.routers.traefik-secure.service=api@internal"

    postgres:
        image: postgres:12
        container_name: mlkafka_postgres_airflow
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        networks:
          - utilities
        volumes:
            - airflow_postgres:/var/lib/postgresql/data
        logging:
            options:
                max-size: 10m
                max-file: "3"

    webserver:
        image: puckel/docker-airflow:latest
        container_name: mlkafka_airflow
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - AIRFLOW__CORE__FERNET_KEY='Y0cy8GGcax-CMFE_8yWIicaX0Fm6wio7T67y3NeKrVg='
#            - SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
        networks:
          - utilities
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - mlkafka_airflow:/usr/local/airflow
            - mlkafka_airflow_packages:/usr/local/lib/python3.7/site-packages
            - ./dags:/usr/local/airflow/dags
            - ./airflow/entrypoint.sh:/entrypoint.sh
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "9999:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.airflow.entrypoints=http"
            - "traefik.http.routers.airflow.rule=Host(`airflow.huhta-lauri.dev`)"
            - "traefik.http.middlewares.airflow-https-redirect.redirectscheme.scheme=https"
            - "traefik.http.routers.airflow.middlewares=airflow-https-redirect"
            - "traefik.http.routers.airflow-secure.entrypoints=https"
            - "traefik.http.routers.airflow-secure.rule=Host(`airflow.huhta-lauri.dev`)"
            - "traefik.http.routers.airflow-secure.tls=true"
            - "traefik.http.routers.airflow-secure.tls.certresolver=http"
            - "traefik.http.routers.airflow-secure.service=airflow"
            - "traefik.http.services.airflow.loadbalancer.server.port=8080"
            - "traefik.docker.network=proxy"


volumes:
  airflow_postgres:
  mlkafka_airflow:
  mlkafka_airflow_packages:

networks:
  utilities:
    driver: bridge
  proxy:
    external: true
  dockerelk_elk:
    external: true
