version: '3.2'
services:
    vault:
        image: vault
        container_name: vault
        ports:
            - "172:17.0.1:8200:8200"
        expose:
          - 8200
        restart: always
        volumes:
            - ./volumes/logs:/vault/logs
            - ./volumes/file:/vault/file
            - ./volumes/config:/vault/config
        cap_add:
            - IPC_LOCK
        entrypoint: vault server -config=/vault/config/vault.json
        networks:
            - utilities
            - dockerelk_elk
            - proxy
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.vault.entrypoints=http"
            - "traefik.http.routers.vault.rule=Host(`vault.huhta-lauri.dev`)"
            - "traefik.http.middlewares.vault-https-redirect.redirectscheme.scheme=https"
            - "traefik.http.routers.vault.middlewares=vault-https-redirect"
            - "traefik.http.routers.vault-secure.entrypoints=https"
            - "traefik.http.routers.vault-secure.rule=Host(`vault.huhta-lauri.dev`)"
            - "traefik.http.routers.vault-secure.tls=true"
            - "traefik.http.routers.vault-secure.tls.certresolver=http"
            - "traefik.http.routers.vault-secure.service=vault"
            - "traefik.http.services.vault.loadbalancer.server.port=8200"
            - "traefik.docker.network=proxy"

    traefik:
      image: traefik:v2.0
      container_name: traefik
      restart: unless-stopped
      security_opt:
        - no-new-privileges:true
      networks:
        - proxy
      ports:
        - 80:80
        - 443:443
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - ./traefik/data/traefik.yml:/traefik.yml:ro
        - ./traefik/data/acme.json:/acme.json
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik.entrypoints=http"
        - "traefik.http.routers.traefik.rule=Host(`traefik.huhta-lauri.dev`)"
        - "traefik.http.middlewares.traefik-auth.basicauth.users=magalorian:$$apr1$$.qEqWkW7$$LoSPOGXQpiHcUht/7Nn3K."
        - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
        - "traefik.http.routers.traefik-secure.entrypoints=https"
        - "traefik.http.routers.traefik-secure.rule=Host(`traefik.huhta-lauri.dev`)"
        - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
        - "traefik.http.routers.traefik-secure.tls=true"
        - "traefik.http.routers.traefik-secure.tls.certresolver=http"
        - "traefik.http.routers.traefik-secure.service=api@internal"

networks:
  utilities:
    driver: bridge
  proxy:
    external: true
  dockerelk_elk:
    external: true
