version: '3.2'
services:
    vault:
        image: vault
        container_name: vault
        ports:
            - "172:17.0.1:8200:8200"
        restart: always
        volumes:
            - ./volumes/logs:/vault/logs
            - ./volumes/file:/vault/file
            - ./volumes/config:/vault/config
        cap_add:
            - IPC_LOCK
        entrypoint: vault server -config=/vault/config/vault.json
        networks:
            - utilities
            - dockerelk_elk
            - proxy
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.vault.entrypoints=http"
            - "traefik.http.routers.vault.rule=Host(`vault.huhta-lauri.dev`)"
            - "traefik.http.middlewares.vault-https-redirect.redirectscheme.scheme=https"
            - "traefik.http.routers.vault.middlewares=vault-https-redirect"
            - "traefik.http.routers.vault-secure.entrypoints=https"
            - "traefik.http.routers.vault-secure.rule=Host(`vault.huhta-lauri.dev`)"
            - "traefik.http.routers.vault-secure.tls=true"
            - "traefik.http.routers.vault-secure.tls.certresolver=http"
            - "traefik.http.routers.vault-secure.service=vault"
            - "traefik.http.services.vault.loadbalancer.server.port=8080"
            - "traefik.docker.network=proxy"

networks:
  utilities:
    driver: bridge
  proxy:
    external: true
  dockerelk_elk:
    external: true